### ISSUE TITLE
Compile errors when building

### ISSUE THREAD

**Issue by devrandomzero** [KellanHiggins/AsciiFBXExporterForUnity#55]
Hi,
when I try to build the project I get 16 errors similar to this:
`Assets/ThirdParty/Fbx_Exporter/Editor/ExporterMenu.cs(57,4): error CS0246: The type or namespace name 'MenuItemAttribute' could not be found (are you missing a using directive or an assembly reference?)`

The Unity version is 2021.3.15f1

In the Editor everything is working correctly

Thank you

**Comment by KellanHiggins** [comment]
Thanks for getting in touch. Turns out I was not excluding the other platforms for the editor files and this was causing issues. If you pull the latest code directly from the github repo, it is fixed. Please let me know if you have other questions.

I will need to update the releases and the asset store now!

**Comment by devrandomzero** [comment]
Thank you! I'll try it as soon as possible!

**Comment by devrandomzero** [comment]
Hi, a bit late (:grin:) but I can confirm that the errors are gone, thank you!

**Comment by KellanHiggins** [comment]
Glad to hear it!
